### ISSUE TITLE
Subscription to mailinglist Spacelog and/or Hout gives a error 500

### ISSUE THREAD

**Issue by HansStroes** [MakerSpaceLeiden/makerspaceleiden-crm#29]
When editing the settings for a new member (Frank Oldenburg), I can activate the subscription for Deelnemers but when I try to do that for the Spacelog- and or Houtmailinglist I receive an Error 500.

**Comment by dirkx** [comment]
Hmm - we’re getting

	mailinglists.mailman.MailmanException: Unknown error - e.g. wrong password

in the log. Will investigate - as the password is correct.

Dw.

**Comment by dirkx** [comment]
I think that it is fixed now. We’ll have to see what happens when the next member is added.

It had to do how we ‘fool’ the Luxemburg system into adding user without admin approval.
