### ISSUE TITLE
Generate the waiver, perhaps as PDF

### ISSUE THREAD

**Issue by dirkx** [MakerSpaceLeiden/makerspaceleiden-crm#3]
So streamline trustee process

**Comment by stefanomasini** [comment]
How should the PDF look like? I've done PDFs in Python in the past, maybe I can help on this one.

**Comment by dirkx** [comment]
So Hugo - who handles them - prefers them on paper. So the process would be create & print & physically post.

So essentially it would be pretty much the current bit of text

	https://github.com/MakerSpaceLeiden/Manuals/blob/master/Verklaring-gevaarlijke-apparatuur.txt

with the users name already filled out. And I guess it would be nice to have a large bar code, date & the user.pk in the corner.

And then perhaps an interface for Hugo where he can simply enter that number on receipt & filing.

**Comment by dirkx** [comment]
@stefanomasini went way over the top! Done !
